### PR TITLE
build: update os image versions

### PR DESCRIPTION
**Pull request by AnqiPang**
Issue #, if available:

*Description of changes:*

*Testing done:*

- [x] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by pendo324** [comment]
Image names look good. Can you also update the core submodule hash when you merge https://github.com/runfinch/finch-core/pull/61? Thanks!

**Comment by pendo324** [comment]
Looks like something broke the "Should print finch version information" test. I'm guessing one of the version numbers of a dependency changed to no longer match the RegEx.

**Comment by AnqiPang** [comment]
> Looks like something broke the "Should print finch version information" test. I'm guessing one of the version numbers of a dependency changed to no longer match the RegEx.

It's weird. I could don't find the version test was executed on the runner amd64 11.7 in the previous run. 
https://github.com/runfinch/finch/actions/runs/4317841292/jobs/7535409441

**Comment by AnqiPang** [comment]
I think it was the suffix ".modified" to the version that caused the version test failure.
` go build -ldflags "-X github.com/runfinch/finch/pkg/version.Version=v0.4.0-21-gf302821.modified -X github.com/runfinch/finch`
In the latest E2E test run, the suffix ".modified" was gone but I don't know the reason. I think it should pass this time.

**Comment by pendo324** [comment]
It was because the git submodule wasn't fully updated. Looks like your last commit fixed it 👍

**Review by pendo324 — APPROVED** [review]

**Pull request merged**
