### PR TITLE
fix: Fix to be able to run finch build with --ssh option

### PR DESCRIPTION
**Pull request by haytok**
In the current implementation, the following error occurs when running finch build with the `--ssh default` option. This issue is also reported in issue/452.

  ```
  error: invalid empty ssh agent socket: make sure SSH_AUTH_SOCK is set
  FATA[0000] no image was built
  FATA[0000] exit status 1
  ```

This is because the ssh agent is not starting on the vm started using lima and the SSH_AUTH_SOCK variable is empty. As a result, this error occurs.

On the other hand, setting forwardAgent to true in finch.yaml will configure the vm to forward the ssh agent.

As a result, the ssh agent will be started in the vm and finch build can be executed using the `--ssh default` option.

Therefore, this commit will fix it so that finch build can be run using the `--ssh default` option.

Issue #, if available: #452

*Description of changes:*

Details are described in commit messages.

*Testing done:*

Yes, confirmation of the operation is added in the comments of the issue below.

- https://github.com/runfinch/finch/issues/452#issuecomment-1810453241

- [x] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mharwani** [comment]
Hi @haytok, is it possible to add e2e tests for `build` with --ssh option? Thanks

**Comment by haytok** [comment]
Hi, @mharwani 

Sure, add an e2e test for the `--ssh` option.

By the way, is it OK if I add the test scenario to the following file?
- https://github.com/runfinch/common-tests/blob/main/tests/build.go

**Comment by mharwani** [comment]
> By the way, is it OK if I add the test scenario to the following test?
> 
>     * https://github.com/runfinch/common-tests/blob/main/tests/build.go

Yes, that's where the tests should go. Feel free to open a PR in that repo and tag me. Thanks

**Comment by haytok** [comment]
Hi, @mharwani 

I have added an e2e test for --ssh option. When you have time, could you please review below PR ? Thanks.

- https://github.com/runfinch/common-tests/pull/101

**Comment by haytok** [comment]
Hi, @mharwani 

I have updated e2e test version from v0.7.8 to v0.7.9 in go.mod and go.sum.

Could you please review when you have time?

**Comment by haytok** [comment]
@mharwani 

Thanks for the advice, I missed the `go mod tidy` failing and the GitHub Actions WF failing.
I've run `go mod tidy` and updated go.mod and go.sum, could you review when you have time?

**Review by mharwani — APPROVED** [review]
LGTM. Thanks!

**Comment by haytok** [comment]
Thanks for merged !

**Pull request merged**
