### PR TITLE
chore: upgrade to go v1.22

### PR DESCRIPTION
**Pull request by pendo324**
Issue #, if available:

*Description of changes:*
- Upgrade `go.mod` and run `go mod tidy`
- Remove unnecessary `brew install go` since we are already using `actions/setup-go` and brew may be outdated

*Testing done:*
- Built finch locally

- [x] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by weikequ — APPROVED** [review]
Looks good! Also pulled changes and ran some tests locally to verify.

**Comment by pendo324** [comment]
> Looks good! Also pulled changes and ran some tests locally to verify.

Thanks! I just uninstalled the homebrew version of Go on all the runners since it was conflicting with the `actions/setup-go` version. Hoping the e2e tests don't all error out this time

**Comment by pendo324** [comment]
@weikequ I made one small change, can you re-review? The test failures seem sporadic -- I've got another PR I want to merge to see if it helps but I'd like to just override merge this one since running any other PR will re-install the Homebrew version of Go, and I'd like to avoid having to uninstall it again.

**Comment by weikequ** [comment]
So I had the 1.22 vs 1.22.0 issue thing as well, but I think it was due to me using brew's version of go (which only goes up to 1.21). Not too sure what the exact cause is.

**Review by weikequ — APPROVED** [review]

**Pull request merged**
