### PR TITLE
docs: Improving Logo

### PR DESCRIPTION
**Pull request by chris-short**
Signed-off-by: Chris Short <cbshort@amazon.com>

Issue #, if available: N/A

*Description of changes:*
Updating the logo in the README

*Testing done:*
Local IDE

- [X] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by pendo324** [comment]
I think the diff is missing adding the new logo file?

**Review by stockholmux — DISMISSED** [review]
LGTM if the logo file is coming in from another PR.

**Comment by chris-short** [comment]
I ❤️ git.

**Review by stockholmux — DISMISSED** [review]
:+1:

**Comment by weikequ** [comment]
@chris-short do we have the light version of the logo? I think we can get the light/dark mode added in using [picture elements.](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)

**Comment by weikequ** [comment]
@chris-short I re-exported the SVG logo with the correct font + added in the light/dark mode logic for the readme.

**Review by KevinLiAWS — APPROVED** [review]

**Pull request merged**
